from __future__ import annotations

from importlib import import_module

__all__ = [
    "CandidateGenerationConfig",
    "CandidateListSample",
    "EpisodeBuildConfig",
    "EpisodeCandidateLists",
    "GRPOTrainConfig",
    "PPOTrainConfig",
    "PreparedRLContext",
    "RLRewardEvaluation",
    "RLTrainerRunner",
    "PPOTrainerRunner",
    "RLOOTrainConfig",
    "RLOOTrainerRunner",
    "RLEpisode",
    "RewardAlignmentReport",
    "RewardConfig",
    "RewardWeights",
    "SelectionConfig",
    "SmallModelSpec",
    "TrainerPreparedArtifacts",
    "build_grpo_prompt_rows",
    "build_strict_rl_prompt_rows",
    "build_prediction_prompt",
    "build_grpo_advantages",
    "build_rl_episodes",
    "compute_reward_alignment",
    "create_trainer_runner",
    "evaluate_rl_reward",
    "generate_episode_candidate_lists",
    "generate_local_predictions",
    "load_candidate_generation_config",
    "load_episode_build_config",
    "load_grpo_train_config",
    "load_ppo_train_config",
    "load_rloo_train_config",
    "load_reward_config",
    "load_selection_config",
    "list_small_model_payloads",
    "list_small_model_specs",
    "parse_completion_predictions",
    "parse_single_completion_prediction",
    "prepare_common_rl_context",
    "resolve_small_model",
    "run_policy_rl_pipeline",
    "select_top_k_predictions",
    "serialize_episodes",
    "serialize_episode_candidate_lists",
    "serialize_reward_evaluation",
    "spearman_correlation",
    "train_grpo_with_verl",
    "train_ppo_with_verl",
    "train_rloo_with_verl",
]

_EXPORTS = {
    "CandidateGenerationConfig": ("forecaster.realization.config", "CandidateGenerationConfig"),
    "EpisodeBuildConfig": ("forecaster.realization.config", "EpisodeBuildConfig"),
    "GRPOTrainConfig": ("forecaster.realization.config", "GRPOTrainConfig"),
    "PPOTrainConfig": ("forecaster.realization.config", "PPOTrainConfig"),
    "RLOOTrainConfig": ("forecaster.realization.config", "RLOOTrainConfig"),
    "RewardConfig": ("forecaster.realization.config", "RewardConfig"),
    "RewardWeights": ("forecaster.realization.config", "RewardWeights"),
    "SelectionConfig": ("forecaster.realization.config", "SelectionConfig"),
    "load_candidate_generation_config": ("forecaster.realization.config", "load_candidate_generation_config"),
    "load_episode_build_config": ("forecaster.realization.config", "load_episode_build_config"),
    "load_grpo_train_config": ("forecaster.realization.config", "load_grpo_train_config"),
    "load_ppo_train_config": ("forecaster.realization.config", "load_ppo_train_config"),
    "load_rloo_train_config": ("forecaster.realization.config", "load_rloo_train_config"),
    "load_reward_config": ("forecaster.realization.config", "load_reward_config"),
    "load_selection_config": ("forecaster.realization.config", "load_selection_config"),
    "CandidateListSample": ("forecaster.realization.candidates", "CandidateListSample"),
    "EpisodeCandidateLists": ("forecaster.realization.candidates", "EpisodeCandidateLists"),
    "RLEpisode": ("forecaster.realization.episodes", "RLEpisode"),
    "build_rl_episodes": ("forecaster.realization.episodes", "build_rl_episodes"),
    "serialize_episodes": ("forecaster.realization.episodes", "serialize_episodes"),
    "RewardAlignmentReport": ("forecaster.realization.grpo", "RewardAlignmentReport"),
    "build_grpo_advantages": ("forecaster.realization.grpo", "build_grpo_advantages"),
    "compute_reward_alignment": ("forecaster.realization.grpo", "compute_reward_alignment"),
    "build_prediction_prompt": ("forecaster.realization.local_generation", "build_prediction_prompt"),
    "generate_local_predictions": ("forecaster.realization.local_generation", "generate_local_predictions"),
    "parse_completion_predictions": ("forecaster.realization.local_generation", "parse_completion_predictions"),
    "parse_single_completion_prediction": ("forecaster.realization.local_generation", "parse_single_completion_prediction"),
    "SmallModelSpec": ("forecaster.realization.model_zoo", "SmallModelSpec"),
    "list_small_model_payloads": ("forecaster.realization.model_zoo", "list_small_model_payloads"),
    "list_small_model_specs": ("forecaster.realization.model_zoo", "list_small_model_specs"),
    "resolve_small_model": ("forecaster.realization.model_zoo", "resolve_small_model"),
    "build_grpo_prompt_rows": ("forecaster.realization.pipeline", "build_grpo_prompt_rows"),
    "build_strict_rl_prompt_rows": ("forecaster.realization.pipeline", "build_strict_rl_prompt_rows"),
    "generate_episode_candidate_lists": ("forecaster.realization.pipeline", "generate_episode_candidate_lists"),
    "prepare_common_rl_context": ("forecaster.realization.pipeline", "prepare_common_rl_context"),
    "run_policy_rl_pipeline": ("forecaster.realization.pipeline", "run_policy_rl_pipeline"),
    "serialize_episode_candidate_lists": ("forecaster.realization.pipeline", "serialize_episode_candidate_lists"),
    "RLRewardEvaluation": ("forecaster.realization.reward", "RLRewardEvaluation"),
    "evaluate_rl_reward": ("forecaster.realization.reward", "evaluate_rl_reward"),
    "serialize_reward_evaluation": ("forecaster.realization.reward", "serialize_reward_evaluation"),
    "spearman_correlation": ("forecaster.realization.reward", "spearman_correlation"),
    "select_top_k_predictions": ("forecaster.realization.selection", "select_top_k_predictions"),
    "PreparedRLContext": ("forecaster.realization.trainers", "PreparedRLContext"),
    "RLTrainerRunner": ("forecaster.realization.trainers", "RLTrainerRunner"),
    "PPOTrainerRunner": ("forecaster.realization.trainers", "PPOTrainerRunner"),
    "RLOOTrainerRunner": ("forecaster.realization.trainers", "RLOOTrainerRunner"),
    "TrainerPreparedArtifacts": ("forecaster.realization.trainers", "TrainerPreparedArtifacts"),
    "create_trainer_runner": ("forecaster.realization.trainers", "create_trainer_runner"),
    "train_grpo_with_verl": ("forecaster.realization.trainers", "train_grpo_with_verl"),
    "train_ppo_with_verl": ("forecaster.realization.trainers", "train_ppo_with_verl"),
    "train_rloo_with_verl": ("forecaster.realization.trainers", "train_rloo_with_verl"),
}


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _EXPORTS[name]
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
